POST http://localhost:8080/api/cards/
Content-Type: application/json

{
  "name": "wrath",
  "count": 2
}

###
PATCH http://localhost:8080/api/cards/a28914a6-d8b2-4396-960c-801a2b01bbdf
Content-Type: application/json

{
  "count": 4,
  "deleted": false
}

###
GET http://localhost:8080/api/cards/

###
DELETE http://localhost:8080/api/cards/c8d2c2c9-20f4-4a89-b592-7590c35b5228

###
GET http://localhost:8080/api/cards/c8d2c2c9-20f4-4a89-b592-7590c35b5228/meta